Repository nwplus/livesite, pull requests merged in 2020-11, with the labels that each got.

#71 Mobile sidebar basic functionality and add mediaQueries breakpoints
  src/assets/menu.svg
  src/components/Common.js
  src/components/MobileMenuBar.js
  src/components/Page.js
  src/components/Sidebar.js
Labels: enhancement

#94 hc bRanD reFrEsH
  src/assets/hc_button.svg
  src/assets/hc_logo.svg
  src/components/Announcements.js
  src/components/Common.js
  src/components/Schedule/Event.js
  src/components/Schedule/Timeline.js
  src/components/Sidebar.js
  src/theme/ThemeProvider.js
Labels: 1pt

#141 fix doc.data() firebase bug
  src/containers/Prizes.js
Labels: bug
